import type { Metadata } from "next";
import "./globals.css";

import { Poppins, Inter } from "next/font/google";
import { QueryProvider } from "@/provider/query-provider";

const fontPoppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

const inter = Inter({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontPoppins.className} ${inter.variable}`}>
      <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
